### ISSUE TITLE
Cannot read property 'version' of null

### ISSUE THREAD

**Issue by redaxmedia** [dimpu/angular2-markdown#102]
Hello,

I just upgraded to version `2.1.0` but this caused my Angular 5 project to faild while building the production dist. There is no problem using `1.6.0`.

# Error

```
ERROR in TypeError: Cannot read property 'version' of null
    at readMetadataFile (/home/project/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:66:29)
    at Object.readMetadata (/home/project/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:35:25)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (/home/project/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:413:34)
    at StaticSymbolResolver.getModuleMetadata (/home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:31804:62)
    at StaticSymbolResolver.hasDecorators (/home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:31531:46)
    at analyzeFile (/home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:30078:63)
    at AotCompiler._analyzeFile (/home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:29306:17)
    at AotCompiler.findGeneratedFileNames (/home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:29322:42)
    at Object.findGeneratedFileNames (/home/project/node_modules/@angular/compiler-cli/src/transformers/program.js:392:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (/home/project/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:325:55)
    at findSourceFile (/home/project/node_modules/typescript/lib/typescript.js:70246:29)
    at processImportedModules (/home/project/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/project/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules (/home/project/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/project/node_modules/typescript/lib/typescript.js:70274:17)
    at args (/home/project/node_modules/typescript/lib/typescript.js:70200:85)
```

# Dependencies

```
"dependencies":
{
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "5.0.2",
    "@angular/common": "5.0.2",
    "@angular/compiler": "5.0.2",
    "@angular/core": "5.0.2",
    "@angular/forms": "5.0.2",
    "@angular/http": "5.0.2",
    "@angular/platform-browser": "5.0.2",
    "@angular/platform-browser-dynamic": "5.0.2",
    "@angular/router": "5.0.2",
    "angular-2-local-storage": "1.0.1",
    "angular2-markdown": "1.6.0",
    "core-js": "2.5.1",
    "harmonize.css": "1.1.1",
    "ng-scrollreveal": "2.1.0",
    "rxjs": "5.5.2",
    "scrollreveal": "3.3.6",
    "zone.js": "0.8.18"
},
"devDependencies":
{
    "@angular/cli": "1.5.3",
    "@angular/compiler-cli": "5.0.2",
    "@angular/language-service": "5.0.2",
    "@types/jasmine": "2.8.2",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.0.53",
    "@types/scrollreveal": "0.0.3",
    "codelyzer": "4.0.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.2.0",
    "ts-node": "3.3.0",
    "tslint": "5.8.0",
    "tslint-eslint-rules": "4.1.1",
    "typescript": "2.4.2"
}
```

# Command

```
ng build --prod
```

**Comment by dimpu** [comment]
@redaxmedia 
Can you try `ng build` to see if you getting any errors?

**Comment by redaxmedia** [comment]
No issues using `ng build`...

1.6.0: https://travis-ci.org/childrenofthedrum/childrenofthedrum-website/builds/305466659
2.1.0: https://travis-ci.org/childrenofthedrum/childrenofthedrum-website/builds/305473420

I missed to report the following error message:

> 10% building modules 3/3 modules 0 activeFailed to read JSON file /mnt/WIP/childrenofthedrum-website/node_modules/angular2-markdown/markdown/prism.languages.metadata.json

**Comment by NikoRoberts** [comment]
Same is happening when I'm building prod with 2.1.0 after upgrading

**Comment by NikoRoberts** [comment]
I think it has to do with polyfills

This is ngx-charts had the same issue with Angular5 support
https://github.com/swimlane/ngx-charts/commit/ce27de37e2ebb97bf5852ddbff6de240119ba4c5

**Comment by MatissJanis** [comment]
I'm experiencing the same issue after upgrading.

**Comment by rernens** [comment]
Here is a workaround.

replace the content of node_modules/angular2-markdown/markdown/prism.languages.metadata.json

[null] 

by 

[]

**Comment by poulad-rbc** [comment]
Same here. Hope this resolves soon.

**Comment by tschuegge** [comment]
Same here:

```
Failed to read JSON file ./node_modules/angular2-markdown/markdown/prism.languages.metadata.json
TypeError: Cannot read property 'version' of null
    at readMetadataFile (./node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:66:29)

```
Please fix _markdown/prism.languages.metadata.json_ in npm package.

**Comment by tschuegge** [comment]
In Version 2.2.0 is the problem not resolved _prism.languages.metadata.json_ already contains _[null]_
