### ISSUE TITLE
Unexpected token import w/ angular-universal

### ISSUE THREAD

**Issue by muffinrecon** [dimpu/angular2-markdown#90]
Getting this error when building server side version of app using angular-universal. Is it because of the es2015 syntax import?

```
node_modules\angular2-markdown\markdown\markdown.component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, ElementRef, Input } from '@angular/core';
```
```
SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.angular2-markdown/markdown/markdown.component 

```

**Comment by dimpu** [comment]
@muffinrecon Sorry. It doesn't support universal yet.
